# Generated by Django 2.0.4 on 2018-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvHumidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Environmental Humidity Value',
                'verbose_name_plural': 'Environmental Humidity Values',
            },
        ),
        migrations.CreateModel(
            name='EnvTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Environmental Temperature Value',
                'verbose_name_plural': 'Environmental Temperature Values',
            },
        ),
        migrations.CreateModel(
            name='IsFilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Water Filling Indicator Value',
                'verbose_name_plural': 'Water Filling Indicator Values',
            },
        ),
        migrations.CreateModel(
            name='IsRain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Rain Indicator Value',
                'verbose_name_plural': 'Rain Indicator Values',
            },
        ),
        migrations.CreateModel(
            name='WaterFlowFishTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Fish Tank Water Flow Indicator Value',
                'verbose_name_plural': 'Fish Tank Water Flow Indicator Values',
            },
        ),
        migrations.CreateModel(
            name='WaterFlowHorizGrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Horizontal Growth Water Flow Indicator Value',
                'verbose_name_plural': 'Horizontal Growth Water Flow Indicator Values',
            },
        ),
        migrations.CreateModel(
            name='WaterFlowMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Main Water Flow Indicator Value',
                'verbose_name_plural': 'Main Water Flow Indicator Values',
            },
        ),
        migrations.CreateModel(
            name='WaterFlowVertGrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Vertical Growth Water Flow Indicator Value',
                'verbose_name_plural': 'Vertical Grow Water Flow Indicator Values',
            },
        ),
        migrations.CreateModel(
            name='WaterLevelFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Full Water Level Indicator Value',
                'verbose_name_plural': 'Full Water Level Indicator Values',
            },
        ),
        migrations.CreateModel(
            name='WaterLevelLow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Low Water Level Indicator Value',
                'verbose_name_plural': 'Low Water Level Indicator Values',
            },
        ),
        migrations.CreateModel(
            name='WaterPH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Water PH Value',
                'verbose_name_plural': 'Water PH Values',
            },
        ),
        migrations.CreateModel(
            name='WaterTempFishTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Fish Tank Water Temperature Value',
                'verbose_name_plural': 'Fish Tank Water Temperature Values',
            },
        ),
        migrations.AlterUniqueTogether(
            name='watertempfishtank',
            unique_together={('value', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='waterph',
            unique_together={('value', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='waterlevellow',
            unique_together={('value', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='waterlevelfull',
            unique_together={('value', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='waterflowvertgrow',
            unique_together={('value', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='waterflowmain',
            unique_together={('value', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='waterflowhorizgrow',
            unique_together={('value', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='waterflowfishtank',
            unique_together={('value', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='israin',
            unique_together={('value', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='isfilling',
            unique_together={('value', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='envtemp',
            unique_together={('value', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='envhumidity',
            unique_together={('value', 'datetime')},
        ),
    ]
